# Site settings
title: Allen's Blog
SEOTitle: Allen的部落格 | Allen's Blog
header-img: img/home-bg.jpg
email: 4103allen@gmail.com
description: "这里是Allen的部落格，分享技術和生活"
keyword: "Allen's Blog, 博客, 个人网站, 互联网, Web, JavaScript, React, 前端, Allen, 攝影, 部落格, 相機, ai, llm, 大模型, claude, gemini, n8n, 程式, docker, 容器化, k8s, 網路, opnsense, Kubernetes, 容器"
url: "https://blog.allenspace.dpdns.org" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
#weibo_username: huxpro
#zhihu_username: huxpro
github_username: allen5218
# twitter_username: huxpro
#facebook_username:  huxpro
linkedin_username:  allen-chang-168934377

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: allen5218

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
# ga_track_id: "UA-49627206-1" # Format: UA-xxxxxx-xx
# ga_domain: blog.allenspace.dpdns.org # 原本是huangxuan.me，要改成blog.allenspace.dpdns.org
# 舊的 UA 格式  google_analytics: UA-xxxxxx-xx
# 新的 GA4 格式  google_analytics: G-xxxxxxxxxx

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "要做一个有 swag 的程序员 <br> React Team @ Meta"
sidebar-avatar: https://avatars.githubusercontent.com/u/100509912?u=ef597a17e92a16e15408260abe9d8eb958698da0&v=4 # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 0 #預設是1 A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
    # { title: "乱序（Midare）", href: "http://mida.re/" },
    # { title: "Ebn Zhang", href: "https://ebnbin.dev/" },
    # { title: "Kun Qian", href: "http://kunq.me" },
    # { title: "Sherry Woo", href: "https://sherrywoo.me/" },
    # { title: "SmdCn", href: "http://blog.smdcn.net" },
    # { title: "JiyinYiyong", href: "http://tiye.me/" },
    # { title: "DHong Say", href: "http://dhong.co" },
    # { title: "尹峰以为", href: "http://ingf.github.io/" },
    { title: "Hux Blog", href: "http://huangxuan.me/" },
  ]
